DROP TABLE IF EXISTS PUBLIC.SALES_ORDER;
CREATE SEQUENCE IF NOT EXISTS PUBLIC.SALES_ORDER_SEQ;

CREATE TABLE PUBLIC.SALES_ORDER(

    ID BIGINT DEFAULT SALES_ORDER_SEQ.nextval,
    SALES_ORDER_ID BIGINT NOT NULL,
    PRIMARY KEY (SALES_ORDER_ID)




);